### ISSUE TITLE
(1) Python 가상환경

### ISSUE THREAD

**Issue by kangraemin** [kangraemin/AWS-Study#1]
## TODO
> Mac 환경을 사용한다는 전제 하에 이슈를 정리하겠습니다. 

- [ ] 가상환경이 무엇인지, 가상환경을 왜 써야하는지 간단히 정리 해 주세요.
- [ ] pip이 무엇인지, 어떨 때 사용하는 것인지 간단히 정리 해 주세요.
- [ ] pipenv가 무엇인지, 어떨 때 사용하는 것인지 간단히 정리 해 주세요. 
- [ ] Homebrew가 무엇인지, 어떨 때 사용하는 것인지 간단히 정리 해 주세요. 
- [ ] Homebrew를 활용하여 pipenv를 설치 해 주세요.
- [ ] pipenv shell이 어떤 역할을 하는지 정리 해 주시고, python 2.7이 설치 되어 있다고 전해 들었으니, pipenv shell을 활용하여 python 3.8을 사용하는 가상환경을 특정 폴더에 구축 해 주세요. 
- [ ] pipenv 가상환경을 비활성화 시키는 명령어를 적어 주세요. 
- [ ] 다시 가상환경을 활성화 시켜주시고, python을 실행 시켜보고 가상환경을 비활성화 시킨 뒤 python을 실행 시켜 보세요. 버전이 다른지 확인 해주세요. 
  - 버전이 다르지 않다면 가상환경이 제대로 구축되지 않은 것일 수 있습니다.
- [ ] pipenv install과, pip install의 차이점을 간단히 정리 해 주세요.
- [ ] `pipenv install django==2.2.10`명령어를 통해 django를 가상환경에 설치 해 주세요.
- [ ] 가상환경을 활성화 시킨 상태에서, python을 실행 해 주시고 아래의 명령어 입력을 통해 django가 제대로 설치 되었는지 확인 해 주세요.
- [ ] 가상환경을 비활성화 시킨 상태에서, python을 실행 해 주시고 아래의 명령어 입력을 통해 가상환경과 다른 환경임을 확인 해 주세요. 
```bash
import django
django.__version__
```
- [ ] 위 작업이 모두 끝나면, 가상환경이 구축된 폴더를 master branch에 commit & push 해주시고, 커밋 메세지에는 `#이슈번호`형식을 남겨 커밋에 해당 이슈를 언급 해 주세요.
