### ISSUE TITLE
(2) Django 샘플 프로젝트 생성

### ISSUE THREAD

**Issue by kangraemin** [kangraemin/AWS-Study#2]
## TODO
> Mac 환경을 사용한다는 전제 하에 이슈를 정리하겠습니다. 
- [ ] 해당 작업은 master branch가 아닌 새로운 Feature branch에서 작업 해 주세요.
- [ ] #1 에서 작업 했던 작업 공간의 가상환경에, `django-admin startproject config`명령어를 활용하여 project를 생성 해 주세요. 
- [ ] 위 명령어를 입력 한 뒤, 첫번째 사진 처럼 되어 있는 프로젝트 구조를 두번째 사진처럼 바꿔 주세요. 
![image](https://user-images.githubusercontent.com/22047559/97450084-ae3c7d80-1975-11eb-8490-bf6236ea6360.png)
![image](https://user-images.githubusercontent.com/22047559/97450138-bf858a00-1975-11eb-8a3f-7f17380e3243.png)
- [ ] `manage.py`가 있는 디렉토리에서, `python manage.py runserver`를 사용하여 django 로컬 서버를 실행 시켜 주세요.
- [x] 로컬 서버 실행 후 화면을 캡처해서 커멘트로 남겨주세요. 
- [ ] python manage.py로 실행 할 수 있는 커멘드 명령어들에 대해 정리 해 주세요. 
- [ ] 위 작업이 끝나면, commit / push 진행 해 주시고, PR을 남겨 주세요.
