### ISSUE TITLE
(3) Django 구조 이해하기 

### ISSUE THREAD

**Issue by kangraemin** [kangraemin/AWS-Study#4]
## TODO
> Mac 환경을 사용한다는 전제 하에 이슈를 정리하겠습니다. 
- [ ] 현재 repo에 Milestone을 추가 하였습니다. github의 milestone이 무엇인지 정리 해 주세요. 
- [ ] 새로운 Feature branch에서 진행 해 주시고, 해당 이슈는 Milestone 1.0에 배정 되었으니, 브랜치 명은 M1.0/snake_case 의 형식으로 진행 해 주시고, 작업의 내용을 대표할 수 있는 단어로 정해주세요
- [ ] createsuperuser 명령어를 통해 superuser 계정을 만들어 주세요. 
- [ ] 로컬에서 서버를 실행시키고, `127.0.0.1:8000/admin`( admin pannel )으로 접속하여 superuser로 로그인 한 뒤 화면을 캡처 해 커멘트에 남겨주세요. 
- [ ] project의 root directory에 startapp 명령어를 통해 channels, users app을 만들어 주세요
- [ ] 위 과정에서 생긴 각 directory에 있는 파일의 용도에 대해서 정리 해 주세요.
- [ ] config에 있는 파일들의 용도에 대해서 정리 해 주세요. 
- [ ] 작업이 하나 끝날 때 마다, check 박스에 체크 해 주세요. 
- [ ] 작업을 모두 마친 뒤, PR을 남겨주세요.

**Comment by HuijungYoon** [comment]
> ## TODO
> > Mac 환경을 사용한다는 전제 하에 이슈를 정리하겠습니다.
> 
> * [x]  현재 repo에 Milestone을 추가 하였습니다. github의 milestone이 무엇인지 정리 해 주세요.
**Milestone**
*******************************************************************************************
마일스톤은 프로젝트에서 주요한 이벤트를 표시하는 기준점이며, 프로젝트 진척을 관찰하기 위해 사용됩니다.
프로젝트의 목표점이나,완성을 의미하는 뜻은 아니지만, 프로젝트가 진행되는 동안 꼭 달성되어야만하는 목표를 가리킵니다.
마일스톤은 프로젝트의 기간에 영향을 주지는 않습니다. 대신 마일 스톤은 꼭 달성해야하는 주요한 목표에 도달하도록 초점을 맞춥니다.

> * [ x]  새로운 Feature branch에서 진행 해 주시고, 해당 이슈는 Milestone 1.0에 배정 되었으니, 브랜치 명은 M1.0/snake_case 의 형식으로 진행 해 주시고, 작업의 내용을 대표할 수 있는 단어로 정해주세요
> * [x]  createsuperuser 명령어를 통해 superuser 계정을 만들어 주세요.

> * [x]  로컬에서 서버를 실행시키고, `127.0.0.1:8000/admin`( admin pannel )으로 접속하여 superuser로 로그인 한 뒤 화면을 캡처 해 커멘트에 남겨주세요.
**capture**
*********************************************************************************************************************************
![스크린샷 2020-10-30 오후 7 03 00](https://user-images.githubusercontent.com/48486487/97692038-90d8f200-1ae2-11eb-9fe1-f339a9141885.png)
> * [x]  project의 root directory에 startapp 명령어를 통해 channels, users app을 만들어 주세요
> * [x]  위 과정에서 생긴 각 directory에 있는 파일의 용도에 대해서 정리 해 주세요.
-       __init__.py: 해당 폴더가 파이썬 모듈로 작동이 가능하도록 해주는 파일
-        admin.py: 관리자가 접속하면 보이는 화면, 내장돼 있음
-        app.py: 앱을 등록하는 기능을 함
-        models.py : 장고 DB 관련된 파일 /  DB 사용계획, 정의, 연결 등의 다양한 설정들을 함
-        tests.py : 테스트를 위한 파이썬 파일
-        views.py : 화면 구성을 위한 파일
-        urls.py :  폴더 안에 없지만, 추가로 생성해서 사용해야 하는 파일
-        migrations/ : 파이썸 모듈로 작동하는 폴더, 데이터 베이스 스키마 관련 역할을 함

> * [x]  config에 있는 파일들의 용도에 대해서 정리 해 주세요.
- __init__.py : 해당 파일의 위치가 Python패키지 디렉터리임을 명시하는 파일이다. 파일 자체가 위치를 안내하는 역할을 한다. 
- settings.py : Django 프로젝트 상의 환경설정을 관리하는 파일. 
- wsgi.py : Web Server Gateway Interface의 약자로 프로젝트의 웹 서비스를 위한 호환 규격을 명시한 파일. 웹 애플리케이션 가동을 위해 필요한 파일이다.
- urls.py : Django 프로젝트의 URL을 관리하는 파일이다. 내가 화면에 주소를 부여해서 접속을 가능하게 해준다. 최초 생성 시에는 admin url이 등록되어 있다.

> * [x]  작업이 하나 끝날 때 마다, check 박스에 체크 해 주세요.
> * [ ]  작업을 모두 마친 뒤, PR을 남겨주세요.
