### ISSUE TITLE
(4) Django 구조 이해하기 - 2

### ISSUE THREAD

**Issue by kangraemin** [kangraemin/AWS-Study#6]
## TODO
> Mac 환경을 사용한다는 전제 하에 이슈를 정리하겠습니다. 
- [ ] config/settings.py 의 `INSTALLED_APPS`에 대해 간략히 정리 해 주세요.
- [ ] config/settings.py 의 `DATABASE`에 대해 간략히 정리 해 주세요.
- [ ] config/settings.py 의 `AUTH_USER_MODEL`에 대해 간략히 정리 해 주세요. 
- [ ] config/settings.py 의 `STATIC_URL`에 대해 간략히 정리 해 주세요. 
- [ ] config/settings.py 의 `SECRET_KEY`에 대해 간략히 정리 해 주세요. 
- [ ] #4 에서 생성한 channels / users 앱을 장고 프로젝트에서 사용 하기 위해 어떠한 작업을 진행 해야 할지 조사 후 진행 해 주세요. 
- [ ] 환경 변수가 어떤 것인지, 왜 필요한 것인지에 대해 간략히 정리 해 주세요.
- [ ] django 프로젝트에서, 환경변수를 어떻게 설정하는지에 대해 간략히 조사 해 주세요.
- [ ] django-dotenv 패키지를 활용하여 settings.py에 있는 SECRET_KEY의 값을 환경 변수로 설정 해 주세요.

**Comment by HuijungYoon** [comment]
> ## TODO
> > Mac 환경을 사용한다는 전제 하에 이슈를 정리하겠습니다.
> 
> * [X]  config/settings.py 의 `INSTALLED_APPS`에 대해 간략히 정리 해 주세요.

 이 파일은 현재 Django 인스턴스에서 활성화된 모든 Django 어플리케이션들의 이름이 담겨 있습니다. 앱들은 다수의 프로젝트에서 사용될 수 있고, 
 다른 프로젝트에서 쉽게 사용될 수 있도록 패키징하여 배포할 수 있습니다.
 새로만든 앱은 이곳에 주소를 추가하여 데이터베이스와 싱크될수 있도록 해주어야한다.
 첫번쨰 경로에는  앱이름 두번째 경로에는 apps다 마지막 경로의 이름은 디폴트로 카멜형식의 app이름+Config으로 만들어 진다.

 ex) 앱이름이 mark일떄
 mark.apps.Markconfig


> * [X]  config/settings.py 의 `DATABASE`에 대해 간략히 정리 해 주세요.
        database엔진에 연결설정하는 항목입니다.

> * [X]  config/settings.py 의 `AUTH_USER_MODEL`에 대해 간략히 정리 해 주세요.

User 모델을 재정의 또는 확장하기 위해서 사용하는 리스트입니다. 장고1.5버전이전에는 모델을 재정의하기가 굉장히 불편했습니다.하지만
장고 1.5버전 이후에는 간단하게 새로운 유저모델을 만들고 AUTH_USER_MODEL에 설정을 해주는것만으로도 확장이 가능해지게되었습니다.

> * [X]  config/settings.py 의 `STATIC_URL`에 대해 간략히 정리 해 주세요.
STATIC_URL은 웹 페이지에서 사용할 정적 파일의 최상위 URL 경로입니다. 이 최상위 경로 자체는 실제 파일이나 디렉터리가 아니며, URL로만 존재하는 단위입니다. 
스태틱에 쓰는 문자열은 마지막에 반드시 '/' 로 끝나야합니다.

> * [x]  config/settings.py 의 `SECRET_KEY`에 대해 간략히 정리 해 주세요.

SECRET_KEY는 장고에 보안과 관련된 항목이다.
장고 공식홈페이지에는 이럴때 쓴다고나와있다.

django.contrib.sessions.backends.cache 이외의 session backend를 사용하고 있거나,
기본 get_session_auth_hash()를 사용하는 모든 sessions
CookieStorage 혹은 FallbackStorage 를 사용하는 모든 messages
모든 PasswordResetView
다른 키가 제공되지 않는 암호화 서명 사용 시 사용된다.

> * [ ]  #4 에서 생성한 channels / users 앱을 장고 프로젝트에서 사용 하기 위해 어떠한 작업을 진행 해야 할지 조사 후 진행 해 주세요.
> * [ ]  환경 변수가 어떤 것인지, 왜 필요한 것인지에 대해 간략히 정리 해 주세요.
> * [ ]  django 프로젝트에서, 환경변수를 어떻게 설정하는지에 대해 간략히 조사 해 주세요.
> * [ ]  django-dotenv 패키지를 활용하여 settings.py에 있는 SECRET_KEY의 값을 환경 변수로 설정 해 주세요.
